package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estaciones generated by hbm2java
 */
@Entity
@Table(name = "estaciones")
public class Estaciones implements java.io.Serializable {

    @Id
    @Column(name = "id_estacion")
    private int idEstacion;
    
    @JoinColumn(name = "zonas_id_zona", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Zonas zonas;
    
    @Column(name = "nombre_estacion")
    private String nombreEstacion;
    
    @Column(name = "portal")
    private Boolean portal;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "estacionesByEstacioneFin")
    private Set<RecorridosHasServicios> recorridosHasServiciosesForEstacioneFin = new HashSet(0);
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "estacionesByEstacionInicio")
    private Set<RecorridosHasServicios> recorridosHasServiciosesForEstacionInicio = new HashSet(0);
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "estaciones")
    private Set<Rutas> rutases = new HashSet(0);

    public Estaciones() {
    }

    public Estaciones(int idEstacion, Zonas zonas, String nombreEstacion) {
        this.idEstacion = idEstacion;
        this.zonas = zonas;
        this.nombreEstacion = nombreEstacion;
    }

    /*public Estaciones(int idEstacion, Zonas zonas, String nombreEstacion, Boolean portal, Set recorridosHasServiciosesForEstacioneFin, Set recorridosHasServiciosesForEstacionInicio, Set rutases) {
        this.idEstacion = idEstacion;
        this.zonas = zonas;
        this.nombreEstacion = nombreEstacion;
        this.portal = portal;
        this.recorridosHasServiciosesForEstacioneFin = recorridosHasServiciosesForEstacioneFin;
        this.recorridosHasServiciosesForEstacionInicio = recorridosHasServiciosesForEstacionInicio;
        this.rutases = rutases;
    }*/

    public int getIdEstacion() {
        return this.idEstacion;
    }

    public void setIdEstacion(int idEstacion) {
        this.idEstacion = idEstacion;
    }

    public Zonas getZonas() {
        return this.zonas;
    }

    public void setZonas(Zonas zonas) {
        this.zonas = zonas;
    }

    public String getNombreEstacion() {
        return this.nombreEstacion;
    }

    public void setNombreEstacion(String nombreEstacion) {
        this.nombreEstacion = nombreEstacion;
    }

    public Boolean getPortal() {
        return this.portal;
    }

    public void setPortal(Boolean portal) {
        this.portal = portal;
    }

    public Set getRecorridosHasServiciosesForEstacioneFin() {
        return this.recorridosHasServiciosesForEstacioneFin;
    }

    public void setRecorridosHasServiciosesForEstacioneFin(Set recorridosHasServiciosesForEstacioneFin) {
        this.recorridosHasServiciosesForEstacioneFin = recorridosHasServiciosesForEstacioneFin;
    }

    public Set getRecorridosHasServiciosesForEstacionInicio() {
        return this.recorridosHasServiciosesForEstacionInicio;
    }

    public void setRecorridosHasServiciosesForEstacionInicio(Set recorridosHasServiciosesForEstacionInicio) {
        this.recorridosHasServiciosesForEstacionInicio = recorridosHasServiciosesForEstacionInicio;
    }

    public Set getRutases() {
        return this.rutases;
    }

    public void setRutases(Set rutases) {
        this.rutases = rutases;
    }

}
