package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;




/**
 * RutasId generated by hbm2java
 */
@Embeddable
public class RutasId  implements java.io.Serializable {


    @Column(name = "servicios_id_servicio", nullable = false)
     private int serviciosIdServicio;
    @Column(name = "estaciones_id_estacion", nullable = false)
     private int estacionesIdEstacion;

    public RutasId() {
    }

    public RutasId(int serviciosIdServicio, int estacionesIdEstacion) {
       this.serviciosIdServicio = serviciosIdServicio;
       this.estacionesIdEstacion = estacionesIdEstacion;
    }
   
    public int getServiciosIdServicio() {
        return this.serviciosIdServicio;
    }
    
    public void setServiciosIdServicio(int serviciosIdServicio) {
        this.serviciosIdServicio = serviciosIdServicio;
    }
    public int getEstacionesIdEstacion() {
        return this.estacionesIdEstacion;
    }
    
    public void setEstacionesIdEstacion(int estacionesIdEstacion) {
        this.estacionesIdEstacion = estacionesIdEstacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RutasId) ) return false;
		 RutasId castOther = ( RutasId ) other; 
         
		 return (this.getServiciosIdServicio()==castOther.getServiciosIdServicio())
 && (this.getEstacionesIdEstacion()==castOther.getEstacionesIdEstacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getServiciosIdServicio();
         result = 37 * result + this.getEstacionesIdEstacion();
         return result;
   }   


}


