package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rutas generated by hbm2java
 */
@Entity
@Table(name = "rutas")
public class Rutas implements java.io.Serializable {

    @EmbeddedId
    private RutasId id;

    @JoinColumn(name = "estaciones_id_estacion", nullable = false, insertable = false, updatable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Estaciones estaciones;

    @JoinColumn(name = "servicios_id_servicio", nullable = false, insertable = false, updatable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Servicios servicios;
    
    @Column(name = "origen")
    private byte origen;
    
    @Column(name = "destino")
    private byte destino;

    public Rutas() {
    }

    public Rutas(RutasId id, Estaciones estaciones, Servicios servicios, byte origen, byte destino) {
        this.id = id;
        this.estaciones = estaciones;
        this.servicios = servicios;
        this.origen = origen;
        this.destino = destino;
    }

    public RutasId getId() {
        return this.id;
    }

    public void setId(RutasId id) {
        this.id = id;
    }

    public Estaciones getEstaciones() {
        return this.estaciones;
    }

    public void setEstaciones(Estaciones estaciones) {
        this.estaciones = estaciones;
    }

    public Servicios getServicios() {
        return this.servicios;
    }

    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }

    public byte getOrigen() {
        return this.origen;
    }

    public void setOrigen(byte origen) {
        this.origen = origen;
    }

    public byte getDestino() {
        return this.destino;
    }

    public void setDestino(byte destino) {
        this.destino = destino;
    }

}
