package modelo;
// Generated 6/10/2020 07:46:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Troncales generated by hbm2java
 */
@Entity
@Table(name = "troncales")
public class Troncales implements java.io.Serializable {

    @Id
    @Column(name = "id_troncal")
    private int idTroncal;
    @Column(name = "nombre_troncal")
    private String nombreTroncal;
    @Column(name = "letra_troncal")
    private String letraTroncal;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "troncales")
    private Set<Zonas> zonases = new HashSet(0);

    public Troncales() {
    }

    public Troncales(int idTroncal, String nombreTroncal, String letraTroncal) {
        this.idTroncal = idTroncal;
        this.nombreTroncal = nombreTroncal;
        this.letraTroncal = letraTroncal;
    }

    public Troncales(int idTroncal, String nombreTroncal, String letraTroncal, Set zonases) {
        this.idTroncal = idTroncal;
        this.nombreTroncal = nombreTroncal;
        this.letraTroncal = letraTroncal;
        this.zonases = zonases;
    }

    public int getIdTroncal() {
        return this.idTroncal;
    }

    public void setIdTroncal(int idTroncal) {
        this.idTroncal = idTroncal;
    }

    public String getNombreTroncal() {
        return this.nombreTroncal;
    }

    public void setNombreTroncal(String nombreTroncal) {
        this.nombreTroncal = nombreTroncal;
    }

    public String getLetraTroncal() {
        return this.letraTroncal;
    }

    public void setLetraTroncal(String letraTroncal) {
        this.letraTroncal = letraTroncal;
    }

    public Set getZonases() {
        return this.zonases;
    }

    public void setZonases(Set zonases) {
        this.zonases = zonases;
    }

}
